const mockState = {
  nextCounselId: 8,
  nextSmeId: 2,
  nextRequestId: 7800,
  nextAdminNotificationId: 1,
  nextPaymentId: 1,
  availability: 'available',
  smeCredits: {
    plan: 'operator',
    includedCredits: 2,
    creditsTotal: 2,
    creditsUsed: 1,
    creditsRemaining: 1,
    usageThisMonth: 1,
    topUpRate: 500,
    currency: 'ZAR',
    resetDate: '2026-07-10',
  },
  smeUsers: new Map([
    ['thabo@company.co.za', {
      userId: 'usr_8f3k2m9x',
      fullName: 'Thabo Molefe',
      email: 'thabo@company.co.za',
      password: '',
      role: 'sme',
      portal: 'sme',
      plan: 'Operator',
      status: 'Active',
      joinedAt: '2025-09-15',
      companyName: 'FibreGents (Pty) Ltd',
      registrationNumber: '2025/123456/07',
      phone: '+27 82 123 4567',
      physicalAddress: '123 Main Street, Sandton, Johannesburg, 2196',
      contactPerson: 'Thabo Molefe',
      updatedAt: '2026-06-10T09:30:00Z',
    }],
    // ── Pre-seeded test accounts with active subscriptions ──────────────────
    // Use these to test the subscriber flow without going through payment.
    // Password for all three: Test@1234
    ['launchpad@tsl.co.za', {
      userId: 'usr_test_lp01',
      fullName: 'Lerato Dlamini',
      email: 'launchpad@tsl.co.za',
      password: 'Test@1234',
      role: 'sme',
      portal: 'sme',
      plan: 'Launchpad',
      status: 'Active',
      joinedAt: '2026-01-01',
      companyName: 'Dlamini Ventures (Pty) Ltd',
      registrationNumber: '2026/000001/07',
      phone: '+27 71 111 0001',
      physicalAddress: '10 Startup Lane, Cape Town, 8001',
      contactPerson: 'Lerato Dlamini',
      updatedAt: '2026-06-01T08:00:00Z',
    }],
    ['operator@tsl.co.za', {
      userId: 'usr_test_op01',
      fullName: 'Sipho Khumalo',
      email: 'operator@tsl.co.za',
      password: 'Test@1234',
      role: 'sme',
      portal: 'sme',
      plan: 'Operator',
      status: 'Active',
      joinedAt: '2026-02-01',
      companyName: 'Khumalo Tech (Pty) Ltd',
      registrationNumber: '2026/000002/07',
      phone: '+27 72 222 0002',
      physicalAddress: '22 Growth Road, Johannesburg, 2196',
      contactPerson: 'Sipho Khumalo',
      updatedAt: '2026-06-01T08:00:00Z',
    }],
    ['boardroom@tsl.co.za', {
      userId: 'usr_test_br01',
      fullName: 'Ayanda Nkosi',
      email: 'boardroom@tsl.co.za',
      password: 'Test@1234',
      role: 'sme',
      portal: 'sme',
      plan: 'Boardroom',
      status: 'Active',
      joinedAt: '2026-03-01',
      companyName: 'Nkosi Holdings (Pty) Ltd',
      registrationNumber: '2026/000003/07',
      phone: '+27 73 333 0003',
      physicalAddress: '33 Corporate Drive, Sandton, 2196',
      contactPerson: 'Ayanda Nkosi',
      updatedAt: '2026-06-01T08:00:00Z',
    }],
  ]),
  adminUsers: new Map([
    ['super@thestartuplegal.co.za', {
      userId: 'adm_000',
      fullName: 'Super Admin',
      firstName: 'Super',
      lastName: 'Admin',
      email: 'super@thestartuplegal.co.za',
      password: '',
      role: 'super_admin',
      portal: 'admin',
      phone: '+27 11 000 0000',
      location: '123 Main Street, Sandton, Johannesburg, 2196',
      jobTitle: 'Super Administrator',
      status: 'active',
      joinedAt: '2025-01-01',
      lastLogin: '',
      updatedAt: '2026-06-10T09:30:00Z',
    }],
    ['given@thestartuplegal.co.za', {
      userId: 'adm_001',
      fullName: 'Given Kibanza',
      firstName: 'Given',
      lastName: 'Kibanza',
      email: 'given@thestartuplegal.co.za',
      password: '',
      role: 'admin',
      portal: 'admin',
      phone: '+27 11 234 5678',
      location: '123 Main Street, Sandton, Johannesburg, 2196',
      jobTitle: 'Platform Administrator',
      status: 'active',
      joinedAt: '2025-12-01',
      lastLogin: 'January 9, 2026 - 14:23',
      updatedAt: '2026-06-10T09:30:00Z',
    }],
  ]),
  counselUsers: new Map([
    ['s.nkosi@tsl.co.za', {
      userId: 'con_002',
      fullName: 'Adv. Sipho Nkosi',
      email: 's.nkosi@tsl.co.za',
      password: 'temporary',
      role: 'counsel',
      portal: 'counsel',
      mustResetPassword: true,
      status: 'active',
    }],
  ]),
  counselDirectory: [
    {
      counselId: 'con_002',
      fullName: 'Adv. Sipho Nkosi',
      name: 'Adv. Sipho Nkosi',
      email: 's.nkosi@tsl.co.za',
      phone: '+27 11 234 5678',
      specialty: 'Commercial & Contract Law',
      expertise: 'SaaS & Technology Contracts',
      status: 'Available',
      availability: 'Available',
      experience: '12 years exp',
      location: 'Johannesburg, Gauteng',
    },
  ],
  adminRequests: [
    {
      requestId: 'req_77b2',
      subject: 'Review of SaaS Service Agreement',
      fromUser: 'Thabo Molefe',
      userEmail: 'thabo@company.co.za',
      company: 'FibreGents (Pty) Ltd',
      receivedAt: '2026-06-10T09:15:00Z',
      submittedAt: '2026-06-10T09:15:00Z',
      status: 'pending',
      description: 'I need a comprehensive review of our SaaS agreement template.',
      assignedBy: 'Admin Sarah',
      earnings: 550,
      currency: 'ZAR',
    },
  ],
  // Mock equivalent of the persisted admin notification/audit table.
  // Seeded with sample data so the bell icon is populated on first load.
  adminNotifications: [
    {
      notificationId: 'notif_login_seed1',
      type: 'login_alert',
      subject: 'New Login Detected',
      message: 'New login to your admin account from Chrome on macOS · IP: 127.0.0.1',
      read: false,
      createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
    {
      notificationId: 'notif_user_seed1',
      type: 'new_user',
      subject: 'New User Registered',
      message: 'Thabo Molefe (thabo@company.co.za) created a new account',
      read: false,
      createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
    {
      notificationId: 'notif_user_seed2',
      type: 'new_user',
      subject: 'New User Registered',
      message: 'Zanele Dlamini (zanele@startup.co.za) created a new account',
      read: true,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      notificationId: 'notif_login_seed2',
      type: 'login_alert',
      subject: 'New Login Detected',
      message: 'New login to your admin account from Safari on iOS · IP: 10.0.0.5',
      read: true,
      createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  paymentTransactions: new Map(),
  counselRequests: [
    {
      requestId: 'req_77b2',
      subject: 'Contract Review for SaaS Agreement',
      fromUser: 'Michael Chen',
      userEmail: 'michael.chen@company.com',
      company: 'FibreGents (Pty) Ltd',
      earnings: 550,
      currency: 'ZAR',
      status: 'pending',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-12',
      assignedAt: '2026-01-12T10:10:00Z',
      timeAgo: '12 min ago',
    },
    {
      requestId: 'req_77b3',
      subject: 'Employment Contract Consultation',
      fromUser: 'Jessica Williams',
      userEmail: 'jessica.w@startup.co.za',
      company: 'Growth Ventures',
      earnings: 450,
      currency: 'ZAR',
      status: 'pending',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-12',
      assignedAt: '2026-01-12T09:57:00Z',
      timeAgo: '25 min ago',
    },
    {
      requestId: 'req_77b4',
      subject: 'Shareholder Agreement Review',
      fromUser: 'David Brown',
      userEmail: 'david.brown@tech.com',
      company: 'Digital Solutions',
      earnings: 550,
      currency: 'ZAR',
      status: 'completed',
      assignedBy: 'Admin John',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-11',
    },
    {
      requestId: 'req_77b5',
      subject: 'NDA Review & Modification',
      fromUser: 'Sarah Johnson',
      userEmail: 'sarah.j@business.co.za',
      company: 'TechStart Inc.',
      earnings: 500,
      currency: 'ZAR',
      status: 'completed',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-10',
    },
    {
      requestId: 'req_77b7',
      subject: 'Intellectual Property Review',
      fromUser: 'Emily Davis',
      userEmail: 'emily.d@innovation.co.za',
      company: 'Innovation Labs',
      earnings: 450,
      currency: 'ZAR',
      status: 'rejected',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-09',
    },
  ],
}

const defaultAssignableCounsel = [
  {
    counselId: 'con_101',
    fullName: 'Sarah Mitchell',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@legaltech.com',
    phone: '+27 11 101 1001',
    specialty: 'SaaS & Technology Contracts',
    expertise: 'SaaS & Technology Contracts',
    status: 'Available',
    availability: 'Available',
    experience: '12 years exp',
    location: 'Johannesburg, Gauteng',
  },
  {
    counselId: 'con_102',
    fullName: 'David Thompson',
    name: 'David Thompson',
    email: 'david.thompson@legaltech.com',
    phone: '+27 11 101 1002',
    specialty: 'Intellectual Property & IP Law',
    expertise: 'Intellectual Property & IP Law',
    status: 'Available',
    availability: 'Available',
    experience: '15 years exp',
    location: 'Cape Town, Western Cape',
  },
  {
    counselId: 'con_103',
    fullName: 'Emily Chen',
    name: 'Emily Chen',
    email: 'emily.chen@legaltech.com',
    phone: '+27 11 101 1003',
    specialty: 'Employment Law & HR Compliance',
    expertise: 'Employment Law & HR Compliance',
    status: 'Busy',
    availability: 'Busy',
    experience: '8 years exp',
    location: 'Durban, KwaZulu-Natal',
  },
  {
    counselId: 'con_104',
    fullName: 'Robert Anderson',
    name: 'Robert Anderson',
    email: 'robert.anderson@legaltech.com',
    phone: '+27 11 101 1004',
    specialty: 'Corporate Law & M&A',
    expertise: 'Corporate Law & M&A',
    status: 'Available',
    availability: 'Available',
    experience: '18 years exp',
    location: 'Pretoria, Gauteng',
  },
  {
    counselId: 'con_105',
    fullName: 'Jennifer Williams',
    name: 'Jennifer Williams',
    email: 'jennifer.williams@legaltech.com',
    phone: '+27 11 101 1005',
    specialty: 'Commercial Contracts & Compliance',
    expertise: 'Commercial Contracts & Compliance',
    status: 'Busy',
    availability: 'Busy',
    experience: '10 years exp',
    location: 'Johannesburg, Gauteng',
  },
  {
    counselId: 'con_106',
    fullName: 'Marcus Rodriguez',
    name: 'Marcus Rodriguez',
    email: 'marcus.rodriguez@legaltech.com',
    phone: '+27 11 101 1006',
    specialty: 'SaaS & Technology Contracts',
    expertise: 'SaaS & Technology Contracts',
    status: 'Available',
    availability: 'Available',
    experience: '6 years exp',
    location: 'Stellenbosch, Western Cape',
  },
  {
    counselId: 'con_107',
    fullName: 'Olivia Zhang',
    name: 'Olivia Zhang',
    email: 'olivia.zhang@legaltech.com',
    phone: '+27 11 101 1007',
    specialty: 'Intellectual Property & IP Law',
    expertise: 'Intellectual Property & IP Law',
    status: 'Available',
    availability: 'Available',
    experience: '14 years exp',
    location: 'Johannesburg, Gauteng',
  },
]

mockState.counselDirectory = defaultAssignableCounsel
defaultAssignableCounsel.forEach((member) => {
  const email = member.email.toLowerCase()
  if (!mockState.counselUsers.has(email)) {
    mockState.counselUsers.set(email, {
      userId: member.counselId,
      fullName: member.fullName,
      email,
      password: 'temporary',
      role: 'counsel',
      portal: 'counsel',
      mustResetPassword: true,
      status: 'active',
      phone: member.phone,
      specialty: member.specialty,
      expertise: member.expertise,
      location: member.location,
      experience: member.experience,
    })
  }
})

// wizardDrafts: Map<userId_wizardType, WizardDraft>
mockState.wizardDrafts = new Map()

const COUNSEL_TIERS = {
  launchpad: { name: 'Launchpad', includedCredits: 0, topUpRate: 550, sla: '2 business days' },
  operator: { name: 'Operator', includedCredits: 2, topUpRate: 500, sla: '1 business day' },
  boardroom: { name: 'Boardroom', includedCredits: 6, topUpRate: 450, sla: '8 business hours' },
}

function resetCounselCreditsIfDue(now = new Date()) {
  const credits = mockState.smeCredits
  let resetAt = new Date(`${credits.resetDate}T00:00:00.000Z`)
  if (Number.isNaN(resetAt.getTime()) || now < resetAt) return credits
  const tier = COUNSEL_TIERS[String(credits.plan || '').toLowerCase()] || COUNSEL_TIERS.operator
  credits.plan = tier.name
  credits.includedCredits = tier.includedCredits
  credits.topUpRate = tier.topUpRate
  credits.creditsTotal = tier.includedCredits
  credits.creditsUsed = 0
  credits.usageThisMonth = 0
  credits.creditsRemaining = tier.includedCredits
  do { resetAt.setUTCMonth(resetAt.getUTCMonth() + 1) } while (resetAt <= now)
  credits.resetDate = resetAt.toISOString().slice(0, 10)
  return credits
}

module.exports = { mockState, COUNSEL_TIERS, resetCounselCreditsIfDue }
