const mockState = {
  nextCounselId: 8,
  nextSmeId: 2,
  nextRequestId: 7800,
  nextPaymentId: 1,
  availability: 'available',
  smeCredits: {
    plan: 'operator',
    creditsTotal: 2,
    creditsUsed: 1,
    creditsRemaining: 1,
    usageThisMonth: 1,
    topUpRate: 500,
    currency: 'ZAR',
    resetDate: '2026-07-10',
  },
  smeUsers: new Map([
    ['thabo@company.co.za', {
      userId: 'usr_8f3k2m9x',
      fullName: 'Thabo Molefe',
      email: 'thabo@company.co.za',
      password: '',
      role: 'sme',
      portal: 'sme',
      plan: 'Operator',
      status: 'Active',
      joinedAt: '2025-09-15',
      companyName: 'FibreGents (Pty) Ltd',
      registrationNumber: '2025/123456/07',
      phone: '+27 82 123 4567',
      physicalAddress: '123 Main Street, Sandton, Johannesburg, 2196',
      contactPerson: 'Thabo Molefe',
      updatedAt: '2026-06-10T09:30:00Z',
    }],
  ]),
  adminUsers: new Map([
    ['given@thestartuplegal.co.za', {
      userId: 'adm_001',
      fullName: 'Given Kibanza',
      firstName: 'Given',
      lastName: 'Kibanza',
      email: 'given@thestartuplegal.co.za',
      password: '',
      role: 'admin',
      portal: 'admin',
      phone: '+27 11 234 5678',
      location: '123 Main Street, Sandton, Johannesburg, 2196',
      jobTitle: 'Platform Administrator',
      status: 'active',
      joinedAt: '2025-12-01',
      lastLogin: 'January 9, 2026 - 14:23',
      updatedAt: '2026-06-10T09:30:00Z',
    }],
  ]),
  counselUsers: new Map([
    ['s.nkosi@tsl.co.za', {
      userId: 'con_002',
      fullName: 'Adv. Sipho Nkosi',
      email: 's.nkosi@tsl.co.za',
      password: 'temporary',
      role: 'counsel',
      portal: 'counsel',
      mustResetPassword: true,
      status: 'active',
    }],
  ]),
  counselDirectory: [
    {
      counselId: 'con_002',
      fullName: 'Adv. Sipho Nkosi',
      name: 'Adv. Sipho Nkosi',
      email: 's.nkosi@tsl.co.za',
      phone: '+27 11 234 5678',
      specialty: 'Commercial & Contract Law',
      expertise: 'SaaS & Technology Contracts',
      status: 'Available',
      availability: 'Available',
      experience: '12 years exp',
      location: 'Johannesburg, Gauteng',
    },
  ],
  adminRequests: [
    {
      requestId: 'req_77b2',
      subject: 'Review of SaaS Service Agreement',
      fromUser: 'Thabo Molefe',
      userEmail: 'thabo@company.co.za',
      company: 'FibreGents (Pty) Ltd',
      receivedAt: '2026-06-10T09:15:00Z',
      submittedAt: '2026-06-10T09:15:00Z',
      status: 'pending',
      description: 'I need a comprehensive review of our SaaS agreement template.',
      assignedBy: 'Admin Sarah',
      earnings: 550,
      currency: 'ZAR',
    },
  ],
  paymentTransactions: new Map(),
  counselRequests: [
    {
      requestId: 'req_77b2',
      subject: 'Contract Review for SaaS Agreement',
      fromUser: 'Michael Chen',
      userEmail: 'michael.chen@company.com',
      company: 'FibreGents (Pty) Ltd',
      earnings: 550,
      currency: 'ZAR',
      status: 'pending',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-12',
      assignedAt: '2026-01-12T10:10:00Z',
      timeAgo: '12 min ago',
    },
    {
      requestId: 'req_77b3',
      subject: 'Employment Contract Consultation',
      fromUser: 'Jessica Williams',
      userEmail: 'jessica.w@startup.co.za',
      company: 'Growth Ventures',
      earnings: 450,
      currency: 'ZAR',
      status: 'pending',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-12',
      assignedAt: '2026-01-12T09:57:00Z',
      timeAgo: '25 min ago',
    },
    {
      requestId: 'req_77b4',
      subject: 'Shareholder Agreement Review',
      fromUser: 'David Brown',
      userEmail: 'david.brown@tech.com',
      company: 'Digital Solutions',
      earnings: 550,
      currency: 'ZAR',
      status: 'accepted',
      assignedBy: 'Admin John',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-11',
    },
    {
      requestId: 'req_77b5',
      subject: 'NDA Review & Modification',
      fromUser: 'Sarah Johnson',
      userEmail: 'sarah.j@business.co.za',
      company: 'TechStart Inc.',
      earnings: 500,
      currency: 'ZAR',
      status: 'accepted',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-10',
    },
    {
      requestId: 'req_77b7',
      subject: 'Intellectual Property Review',
      fromUser: 'Emily Davis',
      userEmail: 'emily.d@innovation.co.za',
      company: 'Innovation Labs',
      earnings: 450,
      currency: 'ZAR',
      status: 'rejected',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-09',
    },
  ],
}

const defaultAssignableCounsel = [
  {
    counselId: 'con_101',
    fullName: 'Sarah Mitchell',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@legaltech.com',
    phone: '+27 11 101 1001',
    specialty: 'SaaS & Technology Contracts',
    expertise: 'SaaS & Technology Contracts',
    status: 'Available',
    availability: 'Available',
    experience: '12 years exp',
    location: 'Johannesburg, Gauteng',
  },
  {
    counselId: 'con_102',
    fullName: 'David Thompson',
    name: 'David Thompson',
    email: 'david.thompson@legaltech.com',
    phone: '+27 11 101 1002',
    specialty: 'Intellectual Property & IP Law',
    expertise: 'Intellectual Property & IP Law',
    status: 'Available',
    availability: 'Available',
    experience: '15 years exp',
    location: 'Cape Town, Western Cape',
  },
  {
    counselId: 'con_103',
    fullName: 'Emily Chen',
    name: 'Emily Chen',
    email: 'emily.chen@legaltech.com',
    phone: '+27 11 101 1003',
    specialty: 'Employment Law & HR Compliance',
    expertise: 'Employment Law & HR Compliance',
    status: 'Busy',
    availability: 'Busy',
    experience: '8 years exp',
    location: 'Durban, KwaZulu-Natal',
  },
  {
    counselId: 'con_104',
    fullName: 'Robert Anderson',
    name: 'Robert Anderson',
    email: 'robert.anderson@legaltech.com',
    phone: '+27 11 101 1004',
    specialty: 'Corporate Law & M&A',
    expertise: 'Corporate Law & M&A',
    status: 'Available',
    availability: 'Available',
    experience: '18 years exp',
    location: 'Pretoria, Gauteng',
  },
  {
    counselId: 'con_105',
    fullName: 'Jennifer Williams',
    name: 'Jennifer Williams',
    email: 'jennifer.williams@legaltech.com',
    phone: '+27 11 101 1005',
    specialty: 'Commercial Contracts & Compliance',
    expertise: 'Commercial Contracts & Compliance',
    status: 'Busy',
    availability: 'Busy',
    experience: '10 years exp',
    location: 'Johannesburg, Gauteng',
  },
  {
    counselId: 'con_106',
    fullName: 'Marcus Rodriguez',
    name: 'Marcus Rodriguez',
    email: 'marcus.rodriguez@legaltech.com',
    phone: '+27 11 101 1006',
    specialty: 'SaaS & Technology Contracts',
    expertise: 'SaaS & Technology Contracts',
    status: 'Available',
    availability: 'Available',
    experience: '6 years exp',
    location: 'Stellenbosch, Western Cape',
  },
  {
    counselId: 'con_107',
    fullName: 'Olivia Zhang',
    name: 'Olivia Zhang',
    email: 'olivia.zhang@legaltech.com',
    phone: '+27 11 101 1007',
    specialty: 'Intellectual Property & IP Law',
    expertise: 'Intellectual Property & IP Law',
    status: 'Available',
    availability: 'Available',
    experience: '14 years exp',
    location: 'Johannesburg, Gauteng',
  },
]

mockState.counselDirectory = defaultAssignableCounsel
defaultAssignableCounsel.forEach((member) => {
  const email = member.email.toLowerCase()
  if (!mockState.counselUsers.has(email)) {
    mockState.counselUsers.set(email, {
      userId: member.counselId,
      fullName: member.fullName,
      email,
      password: 'temporary',
      role: 'counsel',
      portal: 'counsel',
      mustResetPassword: true,
      status: 'active',
      phone: member.phone,
      specialty: member.specialty,
      expertise: member.expertise,
      location: member.location,
      experience: member.experience,
    })
  }
})

// wizardDrafts: Map<userId_wizardType, WizardDraft>
mockState.wizardDrafts = new Map()

module.exports = { mockState }
