const mockState = {
  nextCounselId: 8,
  nextSmeId: 2,
  nextRequestId: 7800,
  availability: 'available',
  smeCredits: {
    plan: 'operator',
    creditsTotal: 2,
    creditsUsed: 1,
    creditsRemaining: 1,
    usageThisMonth: 1,
    topUpRate: 500,
    currency: 'ZAR',
    resetDate: '2026-07-10',
  },
  smeUsers: new Map([
    ['thabo@company.co.za', {
      userId: 'usr_8f3k2m9x',
      fullName: 'Thabo Molefe',
      email: 'thabo@company.co.za',
      role: 'sme',
      portal: 'sme',
      plan: 'Operator',
      status: 'Active',
      joinedAt: '2025-09-15',
      companyName: 'FibreGents (Pty) Ltd',
      registrationNumber: '2025/123456/07',
      phone: '+27 82 123 4567',
      physicalAddress: '123 Main Street, Sandton, Johannesburg, 2196',
      contactPerson: 'Thabo Molefe',
      updatedAt: '2026-06-10T09:30:00Z',
    }],
  ]),
  counselUsers: new Map([
    ['s.nkosi@tsl.co.za', {
      userId: 'con_002',
      fullName: 'Adv. Sipho Nkosi',
      email: 's.nkosi@tsl.co.za',
      password: 'temporary',
      role: 'counsel',
      portal: 'counsel',
      mustResetPassword: true,
      status: 'active',
    }],
  ]),
  counselDirectory: [
    {
      counselId: 'con_002',
      fullName: 'Adv. Sipho Nkosi',
      name: 'Adv. Sipho Nkosi',
      email: 's.nkosi@tsl.co.za',
      phone: '+27 11 234 5678',
      specialty: 'Commercial & Contract Law',
      expertise: 'SaaS & Technology Contracts',
      status: 'Available',
      availability: 'Available',
      experience: '12 years exp',
      location: 'Johannesburg, Gauteng',
    },
  ],
  adminRequests: [
    {
      requestId: 'req_77b2',
      subject: 'Review of SaaS Service Agreement',
      fromUser: 'Thabo Molefe',
      userEmail: 'thabo@company.co.za',
      company: 'FibreGents (Pty) Ltd',
      receivedAt: '2026-06-10T09:15:00Z',
      submittedAt: '2026-06-10T09:15:00Z',
      status: 'pending',
      description: 'I need a comprehensive review of our SaaS agreement template.',
      assignedBy: 'Admin Sarah',
      earnings: 550,
      currency: 'ZAR',
    },
  ],
  counselRequests: [
    {
      requestId: 'req_77b2',
      subject: 'Contract Review for SaaS Agreement',
      fromUser: 'Michael Chen',
      userEmail: 'michael.chen@company.com',
      company: 'FibreGents (Pty) Ltd',
      earnings: 550,
      currency: 'ZAR',
      status: 'pending',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-12',
      assignedAt: '2026-01-12T10:10:00Z',
      timeAgo: '12 min ago',
    },
    {
      requestId: 'req_77b3',
      subject: 'Employment Contract Consultation',
      fromUser: 'Jessica Williams',
      userEmail: 'jessica.w@startup.co.za',
      company: 'Growth Ventures',
      earnings: 450,
      currency: 'ZAR',
      status: 'pending',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-12',
      assignedAt: '2026-01-12T09:57:00Z',
      timeAgo: '25 min ago',
    },
    {
      requestId: 'req_77b4',
      subject: 'Shareholder Agreement Review',
      fromUser: 'David Brown',
      userEmail: 'david.brown@tech.com',
      company: 'Digital Solutions',
      earnings: 550,
      currency: 'ZAR',
      status: 'accepted',
      assignedBy: 'Admin John',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-11',
    },
    {
      requestId: 'req_77b5',
      subject: 'NDA Review & Modification',
      fromUser: 'Sarah Johnson',
      userEmail: 'sarah.j@business.co.za',
      company: 'TechStart Inc.',
      earnings: 500,
      currency: 'ZAR',
      status: 'accepted',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-10',
    },
    {
      requestId: 'req_77b7',
      subject: 'Intellectual Property Review',
      fromUser: 'Emily Davis',
      userEmail: 'emily.d@innovation.co.za',
      company: 'Innovation Labs',
      earnings: 450,
      currency: 'ZAR',
      status: 'rejected',
      assignedBy: 'Admin Sarah',
      assignedCounselId: 'con_002',
      assignedCounselEmail: 's.nkosi@tsl.co.za',
      date: '2026-01-09',
    },
  ],
}

module.exports = { mockState }
